### ISSUE TITLE
allow_session_lost documentation for ChildWatchers seems

### ISSUE THREAD

**Issue by jimfulton** [python-zk/kazoo#156]
The documentation says:

"If allow_session_lost is set to True, then the function will no longer be called if the session is lost."

But:

```
>>> import kazoo.client
>>> c = kazoo.client.KazooClient('localhost:2182')
>>> c2 = kazoo.client.KazooClient('localhost:2183')
```

I have 2 connections against 2 tunnels.

```
>>> @c.add_listener
... def _(state):
...     print state
... 
>>> c.start()
CONNECTED
>>> c2.start()
>>> @c.ChildrenWatch('/test', allow_session_lost=True)
... def _(data):
...     print True, data
... 
True [u'b', u'a', u'aa', u'z']
>>> @c.ChildrenWatch('/test', allow_session_lost=False)
... def _(data):
...     print False, data
... 
False [u'b', u'a', u'aa', u'z']
```

I break the first tunnel

```
SUSPENDED
```

Wait a while and recreate it:

```
LOST
CONNECTED

>>> _ = c2.delete('test/a')
True [u'b', u'aa', u'z']

>>> _ = c2.create('test/a')
True [u'b', u'a', u'aa', u'z']
```

Note that the session is lost when `allow_session_lost` is false, not when is True. Is this a bug? doc bug?

**Comment by bbangert** [comment]
Closing this as I'm not sure if it's still an issue. Changes have been made, etc. Watchers now restore on reconnect as well which could alter this.

**Comment by l2dy** [comment]
> Closing this as I'm not sure if it's still an issue. Changes have been made, etc. Watchers now restore on reconnect as well which could alter this.

The [documentation](https://kazoo.readthedocs.io/en/latest/basic_usage.html#watchers) suggests that if `allow_session_lost` is set to **True**, the function will no longer be called if the session is lost. However, the `test_child_stop_on_session_loss` test in `test_watchers.py` expects that it won't be called when `allow_session_lost` is set to *False* after session loss. Which is the expected behavior?
