### ISSUE TITLE
retry failure in Lock.acquire() may lead to an AttributeError

### ISSUE THREAD

**Issue by arnimarj** [python-zk/kazoo#288]
I've hit on the following exception, on at least one occasion:

.../lib/python2.7/site-packages/kazoo/recipe/lock.py:123, self._delete_node(self.node)", "'AttributeError: 'Lock' object has no attribute 'node'

Calling Lock.acquire(), whilst unconditionally raising RetryFailedError under Retry.__call__() reproduces the bug.

**Comment by harlowja** [comment]
Wanna submit a PR for this? Probably something simple missing.

**Comment by arnimarj** [comment]
The patch is simple enough, but I don't have a reliable test-case. There is an edge case we're triggering in production, but those are rare.

**Comment by sasmith** [comment]
I have a diff essentially ready for this, but want to make sure that I understand the philosophy right before I submit.

The repro I have is that if I create a lock to a path without a leading slash (eg, "foo/bar") and if I set the lock timeout lock enough, then I get the above error. This comes from the fact that in the first call to `_inner_acquire`, `node` is computed incorrectly, and with a sufficiently small timeout, there's never a second call to `_inner_acquire`. The fix I have makes the calculation of `node` more robust.

But the question I have is: are paths without leading slashed supported? I've been using them without problems so far (the leading slash is automatically added at some level, I believe). If the philosophy is that they should be supported, then I think my diff is good. But if not, then it seems like I should write a diff that adds assertions that no paths without leading slashes are provided.

**Comment by sasmith** [comment]
Actually, I figured I'd just submit the PR and then let people decide if this is the way to go.

**Comment by kormat** [comment]
I can reproduce the original issue fairly easily, by emulating packet loss to the Zookeeper service. There's another related issue, caused by the same root issue.

In the 'startup' case, the lock node has not yet been created, and the ZK connection happens to drop at the start of `_inner_acquire`. The `ensure`/`create` calls then causes a `RetryFailedError` to be raised. The handler in `acquire` tries `_best_effort_cleanup`, but then lets execution continue. The `_delete_node` call at the end of `acquire` then fails, as `self.node` is undefined. This case i can reproduce maybe 5% of the time with 50% packet loss. Here's a backtrace snippet:
```
...
  File "<redacted>/kazoo/recipe/lock.py", line 195, in acquire
    self._delete_node(self.node)
AttributeError: 'Lock' object has no attribute 'node'
```

The "running" case is very similar, it just additionally requires that `Lock.release` was called at some previous point, which means that `self.node` is set to `None`. Connection dropping in `_inner_acquire` now causes:
```
...
  File "<redacted>/kazoo/recipe/lock.py", line 195, in acquire
    self._delete_node(self.node)
  File "<redacted>/kazoo/recipe/lock.py", line 300, in _delete_node
    self.client.delete(self.path + "/" + node)
TypeError: Can't convert 'NoneType' object to str implicitly
```
