### ISSUE TITLE
Remove runtime requirements on nose, mock, flake8

### ISSUE THREAD

**Issue by mrocklin** [python-zk/kazoo#478]
This library currently lists runtime requirements on testing libraries like `nose`, `mock`, and `flake8` in requirements.txt.  Are these libraries necessary for using `kazoo` or are they only necessary for testing?  If the latter then you may prefer to not list them as installation requirements.  This can cause some bloat for downstream users, especially those in constrained environments like docker containers.

**Comment by jeffwidman** [comment]
After looking at this a little, I'm confused. Typically, installation requirements for a library are defined in `setup.py`, and any `requirements.txt` is typically only used when hacking on the library.

Currently `setup.py` only lists `six` as a dependency: https://github.com/python-zk/kazoo/blob/master/setup.py#L20

`Requirements.txt` lists those extra dependencies because it's used for dev/testing purposes, where you _would_ want those libs. 

Do I miss something?

**Comment by mrocklin** [comment]
OK, my mistake.  Closing.b
