### ISSUE TITLE
why not support "Asyncio handler"

### ISSUE THREAD

**Issue by EchoShoot** [python-zk/kazoo#499]
I sincere recommend  kazoo to support asyncio handler, 
your know twisted can be transform object from asyncio , 
in the future, may more and more Asynchronous framework can be transform object from asyncio!
i meaning that it will support a lot of frameworks if kazoo support asyncio!

-- your loyal fans

**Comment by tonyseek** [comment]
The current implementation of connection routine uses blocked-style `handler.select`. It works well with monkey patch based solutions but does not work with asyncio.

In my opinion, this is a price for that asyncio chooses to use explicit scheduling and introduces new backward-incompatible syntax. So many libraries are hard to adapt asyncio without breaking Python 2.x users. Even the standard DBAPI2 and WSGI libraries and frameworks could not be adapted too. Adapting native asyncio means maintaining a standalone branch for Python 3.x users only, just like what Gunicorn do.

For Kazoo, using threading handler in Python 3.x + asyncio many be fine enough, since Python 3.x has resolved the performance problem of GIL when multi-threading is enabled.
