### ISSUE TITLE
Watching a Lock

### ISSUE THREAD

**Issue by rjemanuele** [python-zk/kazoo#555]
Is it possible to watch a lock?

After I have a lock, I'd like to watch it in case that portion of the ZK tree is removed.  If the lock is removed, my program that has taken that lock should exit.

Is that possible with the current system?

**Comment by bbangert** [comment]
Sure, if you have the Lock object you'll want to watch the`lock_obj.create_path` node per https://github.com/python-zk/kazoo/blob/master/kazoo/recipe/lock.py#L110. You can setup a watch to be notified of changes to it or its parent.

Honestly, I really hope you don't have code deleting arbitrary Zookeeper trees and nodes such that you need to watch for this as that's a whole new world of pain. 🤕

**Comment by rjemanuele** [comment]
@bbangert Great, thank you!  So your last sentence gives me pause....  We're using zookeeper for configuration management of worker processes.  Some analogous examples:

```
/transportation/road/car
/transportation/road/bus
/transportation/road/truck
/transportation/air/plane
/transportation/air/glider
/transportation/air/chopper
/transportation/water/boat
```

We have processes come up and lock each those nodes, 1 node/process in a cluster.   That process then performs actions based on what node it has locked and the type of node it is (eg. air, road, water, etc).

If a node was to be deleted, ideally that process holding it would return to an idle state or the cluster would scale down.

Based on your comment, this may be a poor use of zookeeper for configuration and locking.  Can you suggest a better practice?

Thank you.

**Comment by bbangert** [comment]
Having the cluster scale down shouldn't disrupt data. Zookeeper is good for configuration and locking, as long as you don't have processes that go through and delete nodes that other processes expect to exist. 

It's important for this reason to use only a single consistent locking system, for example the locking scheme used in kazoo differs slightly from ones implemented using Zookeeper in Java. So one shouldn't try and mix them since they allocate and structure their lock nodes differently.

If the only processes accessing your Zookeeper is kazoo locks, they will not delete each others nodes. And if the client goes away, the node it made will be deleted on its own to avoid blocking other processes attempting to acquire the lock.

The scenario you describe is quite disconcerting, because it implies you have some outside process that deletes nodes for some unknown reason. If you deleted the lock holder node, even if the code did try to watch it, it's quite likely that another node 'in line' for the lock would immediately assume it has a lock and begin. All before the prior lock holder might have a chance to react.
